from r-base
maintainer bioplat

run ["apt-get", "update"]
run ["apt-get", "install", "-y", "libxml2-dev"]


#third dependencies
add libs-to-install.r /r/libs-to-install.r

run ["Rscript", "/r/libs-to-install.r"]


