#!/bin/bash -x

set -e

mode=${1?"indicar modo: prod o dev"}

case $mode in
   "dev")
	port=1180
	sudocmd=""
	;;
   "prod")
	port=80
	sudocmd="sudo"
	;;
   *)
	echo "$mode not valid" && exit 1
esac
	
$sudocmd docker run \
	--volume $(readlink -f webapps-$mode):/opt/tomcat/webapps \
	--volume "$(readlink -f logs-$mode)":/r/logs \
	--volume /etc/timezone:/etc/timezone:ro \
	--publish $port:80  \
	--restart always \
	--detach \
 	--name http-r-server-$mode \
	http-r-server:${mode/dev/latest} $@
	
echo "^C para cortar el log sin terminar el container"
docker logs -f http-r-server-$mode
